main:
    params: [input]
    steps:
    - callback:
        call: http.post
        args:
            url: ${callback_url}
            body: $${input}
            auth:
                type: OIDC
        result: callback_result

    - complete:
        return: '$${callback_result}'
