main:
    params: [input]
    steps:
    - callback:
        call: http.post
        args:
            url: ${callback_url}
            body:
                task: $${input}
                result:
                    message: "Tests completed successfully"
                    status: "passed"
            auth:
                type: OIDC
        result: callback_result

    - complete:
        return: '$${callback_result}'
