main:
    params: [input]
    steps:

    - wimi:
        call: http.get
        args:
            url: https://ipinfo.io/ip
        result: wimi_result
        next: callback

    - callback:
        call: http.post
        args:
            url: ${callback_url}
            body:
                task: $${input}
                result:
                    message: $${"Tests completed successfully from IP address " + wimi_result.body}
                    status: "passed"
            auth:
                type: OIDC
        result: callback_result

    - complete:
        return: '$${callback_result}'
